providerConfig:
  name: default
rbac:
  enabled: true
  roleCatalog:
    fixedPath: catalog/fixed-roles.yaml
    pluginPath: catalog/stacks/default/plugin-roles.yaml
    presetPath: catalog/role-presets.yaml
