{{- $folders := (include "grafana-crossplane.foldersList" . | fromYaml).folders | default list -}}
{{- $fPermMap := (include "grafana-crossplane.folderPermissionsMap" . | fromYaml) | default dict -}}
{{- range $f := $folders }}
{{- $uid := $f.uid | default (include "grafana-crossplane.slugify" $f.title) }}

---

apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: {{ include "grafana-crossplane.resourceName" $uid | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "grafana-crossplane.labels" $ | nindent 4 }}
spec:
  {{- include "grafana-crossplane.providerConfigRef" $ | nindent 2 }}
  managementPolicies:
    - Observe
    - Create
    - Update

  forProvider:
    title: {{ $f.title | quote }}
    uid: {{ $uid | quote }}
    preventDestroyIfNotEmpty: true
    {{- with ($f.parentFolderUid | default $f.parentUid) }}
    parentFolderUid: {{ . | quote }}
    {{- else with $f.parentTitle }}
    parentFolderUid: {{ include "grafana-crossplane.slugify" (. | toString | trim) | quote }}
    {{- end }}

{{- if hasKey $fPermMap $uid }}
{{- $perms := get $fPermMap $uid }}
{{- if $perms }}

---
apiVersion: oss.grafana.m.crossplane.io/v1alpha1
kind: FolderPermission
metadata:
  name: {{ include "grafana-crossplane.resourceName" $uid | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "grafana-crossplane.labels" $ | nindent 4 }}
spec:
  {{- include "grafana-crossplane.providerConfigRef" $ | nindent 2 }}
  forProvider:
    folderUid: {{ $uid | quote }}
    permissions:
      {{- range $p := $perms }}
      - permission: {{ $p.permission | quote }}
        {{- if $p.role }}
        role: {{ $p.role | quote }}
        {{- end }}
        {{- if $p.teamRef }}
        teamRef:
          name: {{ $p.teamRef.name | quote }}
        {{- end }}
        {{- if $p.userRef }}
        userRef:
          name: {{ $p.userRef.name | quote }}
        {{- end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
