apiVersion: 1
contactPoints:
  - orgId: 1
    name: aas-dev-email
    receivers:
      - type: email
        settings:
          addresses: aas-dev@example.com
          singleEmail: false
        disableResolveMessage: false
  - orgId: 1
    name: Monitoring
    receivers:
      - type: email
        settings:
          addresses: monitoring@example.com
          singleEmail: false
        disableResolveMessage: false
  - orgId: 1
    name: NOC Monitoring
    receivers:
      - type: email
        settings:
          addresses: noc-monitoring@example.com
          singleEmail: false
        disableResolveMessage: false