- name: fixed:advisor.checks:reader
  uid: fixed_KQebowM1-87i6O9xQiINqBczxxo
- name: fixed:advisor.checks:writer
  uid: fixed_v_IAfyu-uIQhLauowRjdod_Tc0c
- name: fixed:advisor.checktypes:reader
  uid: fixed_ARymHdS191yuktsn-GTZqpWHbdk
- name: fixed:advisor.checktypes:writer
  uid: fixed_scMeHHoUmtR3bDDla9Tk_h6EA-k
- name: fixed:advisor.register:writer
  uid: fixed_n8bHgQLNCiOBJOMSDSFkgxRmCDI
- name: fixed:advisor.translations:reader
  uid: fixed_OJK8YPYtDzrqOo3HadDF7kSyKR0
- name: fixed:alerting.alertmanager-imports:writer
  uid: fixed_tKsnflM69PHBFvDKdlsuXVvdwG0
- name: fixed:alerting.enrichments:reader
  uid: fixed_1MHLtSHR6cALrgyVttGwW4nmBVE
- name: fixed:alerting.enrichments:writer
  uid: fixed_HKLeTcYmHcm64lzJ5gYKOTQ8sg8
- name: fixed:alerting.inhibition-rules:reader
  uid: fixed_pC-Ofc7pvmj7Yyfc7oliu67RxEQ
- name: fixed:alerting.inhibition-rules:writer
  uid: fixed_0uRAEVdAXFyxEuqoVhspH6DjvKc
- name: fixed:alerting.instances:reader
  uid: fixed_ut5fVS-Ulh_ejFoskFhJT_rYg0Y
- name: fixed:alerting.instances:writer
  uid: fixed_pKOBJE346uyqMLdgWbk1NsQfEl0
- name: fixed:alerting.managed-routes:creator
  uid: fixed_bw49IoZC6KEicSfgNxNEuukxXa4
- name: fixed:alerting.notifications.config:reader
  uid: fixed_81ewa_t30G_KtKCYXLOlhYoixbg
- name: fixed:alerting.notifications.config:writer
  uid: fixed_JUJgqtKuWByW6o3ggE73E7yioas
- name: fixed:alerting.notifications.external:reader
  uid: fixed_rWNhdHUNdZkN8S6e5LAmKKtWt2w
- name: fixed:alerting.notifications.external:writer
  uid: fixed_TSFB5oWYpd8nZgEUeQ0h4FyGmH0
- name: fixed:alerting.notifications:reader
  uid: fixed_hmBn0lX5h1RZXB9Vaot420EEdA0
- name: fixed:alerting.notifications:writer
  uid: fixed_XplK6HPNxf9AP5IGTdB5Iun4tJc
- name: fixed:alerting.provisioning.provenance:writer
  uid: fixed_TORFtFQiHgSlTGnW-ofLa0b3rxI
- name: fixed:alerting.provisioning.secrets:reader
  uid: fixed_9fmzXXZZG-Od0Amy2ofEG8Uk--c
- name: fixed:alerting.provisioning:writer
  uid: fixed_y7pFjdEkxpx5ETdcxPvp0AgRuUo
- name: fixed:alerting.receivers:creator
  uid: fixed_h-ZX5WBw4bfcmzFStUF3_IWfngk
- name: fixed:alerting.receivers:reader
  uid: fixed_e7HL8sF-9P8aZwmKqhN45Ob0WOI
- name: fixed:alerting.receivers:writer
  uid: fixed_XWX0KuQZNhgVXmzmQPFpdX5cArU
- name: fixed:alerting.routes:reader
  uid: fixed_ByG4cCa4s9Jc_VpRwq80y_jypcQ
- name: fixed:alerting.routes:writer
  uid: fixed_uSfE2ZCFozB2VvCU9B7R-adgkg4
- name: fixed:alerting.rules:reader
  uid: fixed_fRGKL_vAqUsmUWq5EYKnOha9DcA
- name: fixed:alerting.rules:writer
  uid: fixed_YJJGwAalUwDZPrXSyFH8GfYBXAc
- name: fixed:alerting.templates:reader
  uid: fixed_irwxMD5Lx5dbHqU7ahIgGc2ssfg
- name: fixed:alerting.templates:writer
  uid: fixed_Ntb782dlLhaBJMLBo2ohdcB3mas
- name: fixed:alerting.time-intervals:reader
  uid: fixed_ENpv0QyUkQYV8WG_c8RHefVMwCE
- name: fixed:alerting.time-intervals:writer
  uid: fixed_J-L93TBpJby55gkKdGdT9F17a0o
- name: fixed:alerting:admin
  uid: fixed_ceFufpsSIv8LgBB81M9_NSHydxg
- name: fixed:alerting:reader
  uid: fixed_O2oP1_uBFozI2i93klAkcvEWR30
- name: fixed:alerting:writer
  uid: fixed_-PAZgSJsDlRD8NUg-PFSeH_BkJY
- name: fixed:annotations.all:reader
  uid: fixed_JA_jZCZLQgjR_K-Ol4z047Fqwzo
- name: fixed:annotations.all:writer
  uid: fixed_-KH4XxwEyEObak_rVvy9dmrlFNw
- name: fixed:annotations:reader
  uid: fixed_hpZnoizrfAJsrceNcNQqWYV-xNU
- name: fixed:annotations:writer
  uid: fixed_ZVW-Aa9Tzle6J4s2aUFcq1StKWE
- name: fixed:authentication.config:writer
  uid: fixed_0rYhZ2Qnzs8AdB1nX7gexk3fHDw
- name: fixed:banners:writer
  uid: fixed_gDi67bZclPA8UuAMVR-TeJv8kh8
- name: fixed:dashboards.insights:reader
  uid: fixed_JlBJ2_gizP8zhgaeGE2rjyZe2Rs
- name: fixed:dashboards.permissions:reader
  uid: fixed_f17oxuXW_58LL8mYJsm4T_mCeIw
- name: fixed:dashboards.permissions:writer
  uid: fixed_CcznxhWX_Yqn8uWMXMQ-b5iFW9k
- name: fixed:dashboards.public:writer
  uid: fixed_f_GHHRBciaqESXfGz2oCcooqHxs
- name: fixed:dashboards:creator
  uid: fixed_ZorKUcEPCM01A1fPakEzGBUyU64
- name: fixed:dashboards:reader
  uid: fixed_Sgr67JTOhjQGFlzYRahOe45TdWM
- name: fixed:dashboards:writer
  uid: fixed_OK2YOQGIoI1G031hVzJB6rAJQAs
- name: fixed:dashboardtemplates:reader
  uid: fixed_rZDjMdg2EKplV0xKrPa5rPlRm0M
- name: fixed:dashboardtemplates:writer
  uid: fixed_6t8K_lMFeGl9c8k-pWOD-CDgN9M
- name: fixed:datasources.caching:reader
  uid: fixed_D2ddpGxJYlw0mbsTS1ek9fj0kj4
- name: fixed:datasources.caching:writer
  uid: fixed_JtFjHr7jd7hSqUYcktKvRvIOGRE
- name: fixed:datasources.id:reader
  uid: fixed_entg--fHmDqWY2-69N0ocawK0Os
- name: fixed:datasources.insights:reader
  uid: fixed_EBZ3NwlfecNPp2p0XcZRC1nfEYk
- name: fixed:datasources.permissions:reader
  uid: fixed_ErYA-cTN3yn4h4GxaVPcawRhiOY
- name: fixed:datasources.permissions:writer
  uid: fixed_aiQh9YDfLOKjQhYasF9_SFUjQiw
- name: fixed:datasources:creator
  uid: fixed_XX8jHREgUt-wo1A-rPXIiFlX6Zw
- name: fixed:datasources:explorer
  uid: fixed_qDzW9mzx9yM91T5Bi8dHUM2muTw
- name: fixed:datasources:reader
  uid: fixed_C2x8IxkiBc1KZVjyYH775T9jNMQ
- name: fixed:datasources:writer
  uid: fixed_q8HXq8kjjA5IlHHgBJlKlUyaNik
- name: fixed:featuremgmt:reader
  uid: fixed_U4tE1bcEggOe8Pkwj8AT_TC8W1A
- name: fixed:featuremgmt:writer
  uid: fixed_bIlWKp0r4boOW6O7UKVH1KH0i9o
- name: fixed:folders.permissions:reader
  uid: fixed_E06l4cx0JFm47EeLBE4nmv3pnSo
- name: fixed:folders.permissions:writer
  uid: fixed_3GAgpQ_hWG8o7-lwNb86_VB37eI
- name: fixed:folders:creator
  uid: fixed_gGLRbZGAGB6n9uECqSh_W382RlQ
- name: fixed:folders:reader
  uid: fixed_yeW-5QPeo-i5PZUIUXMlAA97GnQ
- name: fixed:folders:writer
  uid: fixed_wJXLoTzgE7jVuz90dryYoiogL0o
- name: fixed:general.auth.config:writer
  uid: fixed_QFxIT_FGtBqbIVJIwx1bLgI5z6c
- name: fixed:kgatlas.ext.grafana.app:kg-atlas:admin
  uid: 36022ba8-e39e-4d22-8a7e-e2197eab4f15
- name: fixed:kgatlas.ext.grafana.app:kg-atlas:editor
  uid: e7d54e58-f33c-470f-b972-3fc2c1fff545
- name: fixed:kgatlas.ext.grafana.app:kg-atlas:reader
  uid: 752c2b1d-dcc2-4395-85ff-1a514a88e21e
- name: fixed:ldap:reader
  uid: fixed_lMcOPwSkxKY-qCK8NMJc5k6izLE
- name: fixed:ldap:writer
  uid: fixed_p6AvnU4GCQyIh7-hbwI-bk3GYnU
- name: fixed:library.panels:creator
  uid: fixed_6eX6ItfegCIY5zLmPqTDW8ZV7KY
- name: fixed:library.panels:general.reader
  uid: fixed_ct0DghiBWR_2BiQm3EvNPDVmpio
- name: fixed:library.panels:general.writer
  uid: fixed_DgprkmqfN_1EhZ2v1_d1fYG8LzI
- name: fixed:library.panels:reader
  uid: fixed_tvTr9CnZ6La5vvUO_U_X1LPnhUs
- name: fixed:library.panels:writer
  uid: fixed_JTljAr21LWLTXCkgfBC4H0lhBC8
- name: fixed:licensing:reader
  uid: fixed_OADpuXvNEylO2Kelu3GIuBXEAYE
- name: fixed:licensing:writer
  uid: fixed_gzbz3rJpQMdaKHt-E4q0PVaKMoE
- name: fixed:live:writer
  uid: fixed_i9dSUw29nVAQnlXrInDOpP_aqAc
- name: fixed:maintwindows.ext.grafana.app:maint-windows:admin
  uid: af73147c-f0f2-434a-91c4-0366df975e25
- name: fixed:maintwindows.ext.grafana.app:maint-windows:viewer
  uid: f9bb20c1-2dad-49eb-8919-08bf7117bd84
- name: fixed:migrationassistant:migrator
  uid: fixed_LLk2p7TRuBztOAksTQb1Klc8YTk
- name: fixed:notifications.alerting.grafana.app:routingtrees.permissions:reader
  uid: fixed_O7zjTgg7qRhY_xbyXcpzrH7sqW8
- name: fixed:notifications.alerting.grafana.app:routingtrees.permissions:writer
  uid: fixed_5vfp5ZISD0mhevK6KFLFcuMp60M
- name: fixed:org.users:reader
  uid: fixed_oCqNwlVHLOpw7-jAlwp4HzYqwGY
- name: fixed:org.users:writer
  uid: fixed_VERj5nayasjgf_Yh0sWqqCkxWlw
- name: fixed:organization:maintainer
  uid: fixed_CMm-uuBaPUBf4r8XG3jIvxo55bg
- name: fixed:organization:reader
  uid: fixed_0SZPJlTHdNEe8zO91zv7Zwiwa2w
- name: fixed:organization:writer
  uid: fixed_Y4jGqDd8w1yCrPwlik8z5Iu8-3M
- name: fixed:pathfinderbackend.ext.grafana.app:pathfinder-backend:completion-writer
  uid: 85f65593-ee40-4607-b5aa-6dfce96fe0de
- name: fixed:pathfinderbackend.ext.grafana.app:pathfinder-backend:guide-editor
  uid: 70ea95cc-df73-439d-8a90-6da7c036a80b
- name: fixed:pathfinderbackend.ext.grafana.app:pathfinder-backend:reader
  uid: 5c3d985b-cb49-4199-9f66-25672a46648d
- name: fixed:playlists:reader
  uid: fixed_F7hCWhf_LtlXdROvtizDXZlhpBw
- name: fixed:playlists:writer
  uid: fixed_8sLPV9RM3THrLbzVMA428SzYyHw
- name: fixed:plugins.app:reader
  uid: fixed_AcZRiNYx7NueYkUqzw1o2OGGUAA
- name: fixed:plugins.metas:reader
  uid: fixed_2W6tVsL0_zJuBka0iV1CNe5NEvY
- name: fixed:plugins.metas:writer
  uid: fixed_4qx5G08ghnMptZB_dTk5Y8ZG7mo
- name: fixed:plugins.plugins:reader
  uid: fixed_hDoUz8FNyHUJT6jOczgdba_uh_Y
- name: fixed:plugins.plugins:writer
  uid: fixed_Tr_xPvXFUGa4gSEQbpX6-WFoRJM
- name: fixed:plugins:maintainer
  uid: fixed_yEOKidBcWgbm74x-nTa3lW5lOyY
- name: fixed:plugins:writer
  uid: fixed_MRYpGk7kpNNwt2VoVOXFiPnQziE
- name: fixed:provisioning.connections:reader
  uid: fixed_R70D-XkDdaw5utTS_BteB14P_MA
- name: fixed:provisioning.connections:writer
  uid: fixed_a40V0_lrYTn144-j_yiBnHs46aM
- name: fixed:provisioning.historicjobs:reader
  uid: fixed_LRxwyFUv4KCsj6cBWlDTDJRs7sA
- name: fixed:provisioning.jobs:reader
  uid: fixed_DBn99lJwPhye5VF3TxgAokizC-I
- name: fixed:provisioning.jobs:writer
  uid: fixed_K1UyhyGOYPcWrHtZ1m14RKHPwS0
- name: fixed:provisioning.repositories:reader
  uid: fixed_8aB9VCet3Iig7aYhaXql5ZAdvUc
- name: fixed:provisioning.repositories:writer
  uid: fixed_rKnVaBKQID4k0FIUg6QfNfKQN1E
- name: fixed:provisioning.settings:reader
  uid: fixed_SvZgD-RwbQY7rW0A2SMfpHHiH5g
- name: fixed:provisioning.stats:reader
  uid: fixed_ASfMwmtm6wQ-c5BaQU4-czXjvoc
- name: fixed:provisioning:writer
  uid: fixed_bgk1FCyR6OEDwhgirZlQgu5LlCA
- name: fixed:queries:reader
  uid: fixed_-rEsxR-pZg1-fQL-XDQaouEpK98
- name: fixed:queries:writer
  uid: fixed_7TMOlueweuPX_PhffesRB2FTQn4
- name: fixed:receivers.permissions:reader
  uid: fixed_HMLJlKe9MOgHOs3vqvzl4Nqkgy4
- name: fixed:receivers.permissions:writer
  uid: fixed_gFAyTppaRi_OoLr0Pk1h7qz4Euk
- name: fixed:reports:reader
  uid: fixed_72_8LU_0ukfm6BdblOw8Z9q-GQ8
- name: fixed:reports:writer
  uid: fixed_jBW3_7g1EWOjGVBYeVRwtFxhUNw
- name: fixed:roles:reader
  uid: fixed_GkfG-1NSwEGb4hpK3-E3qHyNltc
- name: fixed:roles:resetter
  uid: fixed_WgPpC3qJRmVpVTJavFNwfS5RuzQ
- name: fixed:roles:writer
  uid: fixed_W5aFaw8isAM27x_eWfElBhZ0iOc
- name: fixed:secret.keepers:reader
  uid: fixed_jzKh0B7CpmY-MJd1Tnhjh_zZF4Q
- name: fixed:secret.keepers:writer
  uid: fixed_L11wNUP3j7bL1JT2fPHWIblYYP4
- name: fixed:secret.securevalues:creator
  uid: fixed_BoxvYJ7Yt485ISJgDiHCouWCx2Q
- name: fixed:secret.securevalues:deleter
  uid: fixed_KB7I9NMtx0HqBQL_tB1rk0ftBmM
- name: fixed:secret.securevalues:reader
  uid: fixed_BJmeHUHcTiJtTlllfygnyVWO_Kc
- name: fixed:secret.securevalues:updater
  uid: fixed_1xSPRCIeqg-PsxCziybCDp1jylQ
- name: fixed:serviceaccounts.permissions:reader
  uid: fixed_0pyblzhcBXxHpTxn_NGQ0vE1XAs
- name: fixed:serviceaccounts.permissions:writer
  uid: fixed_cqblNJc6_iOatnMuwbrVh5u2XQo
- name: fixed:serviceaccounts:creator
  uid: fixed_Ikw60fckA0MyiiZ73BawSfOULy4
- name: fixed:serviceaccounts:reader
  uid: fixed_QFjJAZ88iawMLInYOxPA1DB1w6I
- name: fixed:serviceaccounts:writer
  uid: fixed_iBvUNUEZBZ7PUW0vdkN5iojc2sk
- name: fixed:settings:reader
  uid: fixed_0LaUt1x6PP8hsZzEBhqPQZFUd8Q
- name: fixed:settings:writer
  uid: fixed_joIHDgMrGg790hMhUufVzcU4j44
- name: fixed:smtp.settings:writer
  uid: fixed_h8fbh151mNilx5Mo1GJjOAOOGg0
- name: fixed:snapshots:creator
  uid: fixed_dAzn7RqEaljJ-QbLbBqjQ9uFt84
- name: fixed:snapshots:deleter
  uid: fixed_x5Nt1nCVP7BrqS5BCDFv83M-1I8
- name: fixed:snapshots:reader
  uid: fixed_JgcVa4iAXbNgftwQIeGxdqhDzCU
- name: fixed:stats:reader
  uid: fixed_OnRCXxZVINWpcKvTF5A1gecJ7pA
- name: fixed:support.bundles:reader
  uid: fixed_gcPjI3PTUJwRx-GJZwDhNa7zbos
- name: fixed:support.bundles:writer
  uid: fixed_dTgCv9Wxrp_WHAhwHYIgeboxKpE
- name: fixed:teams.permissions:reader
  uid: fixed_JIn-Mrnm4avL-3x_BoT3WOzRXWo
- name: fixed:teams.permissions:writer
  uid: fixed_klHrAnRMf3lY64KLtb3P4Chzy3Y
- name: fixed:teams:creator
  uid: fixed_nzVQoNSDSn0fg1MDgO6XnZX2RZI
- name: fixed:teams:read
  uid: fixed_Z8pB0GQlrqRt8IZBCJQxPWvJPgQ
- name: fixed:teams:writer
  uid: fixed_xw1T0579h620MOYi4L96GUs7fZY
- name: fixed:usagestats:reader
  uid: fixed_eAM0azEvnWFCJAjNkUKnGL_1-bU
- name: fixed:users:reader
  uid: fixed_buZastUG3reWyQpPemcWjGqPAd0
- name: fixed:users:writer
  uid: fixed_wjzgHHo_Ux25DJuELn_oiAdB_yM
