slos:
  - name: test-api-availability
    description: "Test SLO for API Availability"
    destinationDatasource:
      - uid: "grafanacloud-prom"
    objectives:
      - value: 0.995
        window: "30d"
    query:
      - type: "freeform"
        freeform:
          - query: "sum(rate(node_cpu_seconds_total{mode!='idle'}[$__rate_interval])) / sum(rate(node_cpu_seconds_total[$__rate_interval]))"
