name: Cyber Security Team
presets:
- observability_viewer
- security_auditor
syncGroups:
- aae130ec-fb9d-4e92-9594-5264b38d722d
folderPermissions:
- folder: cyber-security-team
  permission: Admin
datasourcePermissions:
- datasource: logs
  permission: Query
lbacSelectors:
- '{ business_unit="osttra", product_name="cybersecurity" }'
