name: DBS Leads
preset: dashboard_editor
syncGroups:
- 91933de0-6820-4fbd-9948-821981bbf6e7
folderPermissions:
- folder: dbs-leads
  permission: Admin
- folder: dbs-contributors
  permission: Admin
- folder: elasticsearch
  permission: Admin
- folder: database-readonly
  permission: Admin
datasourcePermissions:
- datasource: logs
  permission: Query
lbacSelectors:
- '{ business_unit!="", business_unit!="reset", business_unit!="trioptima", business_unit!="osttra"
  }'
