name: group admins
preset: admin
syncGroups:
- 5e638c4b-c743-469b-980b-22db9c6d4ba4
folderPermissions:
- folder: group-admins
  permission: Admin
datasourcePermissions:
- datasource: logs
  permission: Query
lbacSelectors:
- '{ business_unit=~".*" }'
