name: optapi
preset: observability_viewer
syncGroups:
- 0d803051-8320-4aae-935f-286db952d40f
folderPermissions:
- folder: optapi
  permission: Admin
datasourcePermissions:
- datasource: logs
  permission: Query
lbacSelectors:
- '{ business_unit="trioptima", product_name="optapi" }'
