apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-crossplane
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: grafana-crossplane
  source:
    repoURL: https://github.com/cosmicsatish/grafana-crossplane.git
    targetRevision: main
    path: chart
    helm:
      releaseName: grafana-crossplane
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    - FailOnSharedResource=true
    - PruneLast=true
    - SkipDryRunOnMissingResource=true
  ignoreDifferences:
  - group: oss.grafana.m.crossplane.io
    kind: FolderPermission
    jqPathExpressions:
    - .spec.forProvider.permissions[].teamId
    - .spec.forProvider.permissions[].userId
  - group: enterprise.grafana.m.crossplane.io
    kind: RoleAssignment
    jsonPointers:
    - /spec/forProvider/teams
    - /spec/forProvider/serviceAccounts

