apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-crossplane
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: grafana-crossplane
  source:
    repoURL: https://github.com/cosmicsatish/grafana-crossplane.git
    targetRevision: main
    path: chart
    helm:
      releaseName: grafana-crossplane
      ignoreMissingValueFiles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    - FailOnSharedResource=true
    - PruneLast=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
