apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grafana-crossplane
  namespace: argocd
spec:
  description: Grafana GitOps control plane managed by Helm and Crossplane
  sourceRepos:
    - "https://github.com/cosmicsatish/grafana-crossplane.git"
  destinations:
    - namespace: crossplane-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
