# Create this Secret outside Git.
# The `credentials` key must contain:
# {"url":"https://<stack>.grafana.net","auth":"<service-account-token>"}
apiVersion: grafana.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: grafana-provider-creds
      key: credentials
