- name: plugins:grafana-adaptive-metrics-app:admin
  uid: plugins_QBiDQQnTy-9_yNzUJ5hXjk7-Suc
- name: plugins:grafana-adaptive-metrics-app:config-editor
  uid: plugins_FEbnkHtM_OqAh1FZF5cdQry8fQA
- name: plugins:grafana-adaptive-metrics-app:config-reader
  uid: plugins_IH14cXO6SnUAoTWn1gsK5ROr8LY
- name: plugins:grafana-adaptive-metrics-app:exemptions-editor
  uid: plugins_t79CNCxk2gsyX1XAntZm8qUYmwI
- name: plugins:grafana-adaptive-metrics-app:exemptions-reader
  uid: plugins_1o-DSXB4Q9M-9dPHhV34A7zBZTc
- name: plugins:grafana-adaptive-metrics-app:plugin-access
  uid: plugins_b3hcFRv0nu_Upo6BJD3az4UO1nY
- name: plugins:grafana-adaptive-metrics-app:rules-editor
  uid: plugins_3uXoOytpHnnYb-RUWDjI_cX7cJo
- name: plugins:grafana-adaptive-metrics-app:rules-reader
  uid: plugins_M1GkAFGQS94uub5AFRIQide1EHQ
- name: plugins:grafana-adaptive-metrics-app:segments-editor
  uid: plugins_-C3tTrVowunezA0AS6GuUS8wqsI
- name: plugins:grafana-adaptive-metrics-app:segments-reader
  uid: plugins_z9Xw19HLSjHXU3ScBO4MYTwivzY
- name: plugins:grafana-adaptivelogs-app:admin
  uid: plugins_XyJZXUOQBTEWvuE9_sGSlr1ZVA4
- name: plugins:grafana-adaptivelogs-app:archive-configuration-admin
  uid: plugins_ZuwlJQfdcIbQXuWAI4ohMJbfjrk
- name: plugins:grafana-adaptivelogs-app:archive-reader
  uid: plugins_gzT_WKezxWdMfH2u9ikMd258aNw
- name: plugins:grafana-adaptivelogs-app:archive-replay-controller
  uid: plugins_otWREOmnHf2kRKXvqMc4ayjYSM8
- name: plugins:grafana-adaptivelogs-app:archive-rules-editor
  uid: plugins_foROCuHp0r9dOofQZGnRKnEQTp8
- name: plugins:grafana-adaptivelogs-app:drop-rules-reader
  uid: plugins_2Lz9_ZXUzH9GVeV0SzQtQLFYVaY
- name: plugins:grafana-adaptivelogs-app:expiring-exemptions-user
  uid: plugins_7mmPJ2aBjXqjHntUw-SoROxscxo
- name: plugins:grafana-adaptivelogs-app:patterns-editor
  uid: plugins_P5mUforfzfTyZZYaYH2K7Uqra8U
- name: plugins:grafana-adaptivelogs-app:patterns-reader
  uid: plugins_j7NAUbu7VYSF9wXJhjBPKjmaiKY
- name: plugins:grafana-adaptivelogs-app:plugin-access
  uid: plugins_IghS20T6wq5rWex17cLYm6jUnvc
- name: plugins:grafana-adaptivelogs-app:segments-admin
  uid: plugins_NPSVnxAjkL5QNL2HRIZP4glTJh4
- name: plugins:grafana-adaptivetraces-app:admin
  uid: plugins_Tlh9OSn52ww7vInbDK0TWIMmzeI
- name: plugins:grafana-agento11y-app:agento11y-admin
  uid: plugins_S9g5YYGWFpQhVU6vzlGzEvDyLCw
- name: plugins:grafana-agento11y-app:agento11y-data-reader
  uid: plugins_T6exmFqLcMoS_Cxn3vutRSPQVRo
- name: plugins:grafana-agento11y-app:agento11y-feedback-writer
  uid: plugins_9WYjF-Ne_Xy9mB6mHAPU5wjBwCg
- name: plugins:grafana-agento11y-app:agento11y-reader
  uid: plugins_GrA1M7xq4UU3SItsBery64lEtvw
- name: plugins:grafana-agento11y-app:agento11y-viewer
  uid: plugins_7MtL7FuCMKcKS3zI5vUeXJ00wg8
- name: plugins:grafana-app-observability-app:admin
  uid: plugins_bZEQFP3cWredKtze3fQ8xOXoh9I
- name: plugins:grafana-app-observability-app:viewer
  uid: plugins_Lneziiee78I4d5me1heTVoZS0hU
- name: plugins:grafana-asserts-app:knowledge-graph-access
  uid: plugins_BkFh5_AJgIL0Gxc48N31A_UFDI8
- name: plugins:grafana-asserts-app:knowledge-graph-reader
  uid: plugins_giQ7iHQ8-4_xFo6StbpoC-Pjx70
- name: plugins:grafana-asserts-app:knowledge-graph-writer
  uid: plugins_UWup9yBiZBaJ81s_SvLf93eI-Z4
- name: plugins:grafana-assistant-app:assistant-admin
  uid: plugins_bA1IkBmtqmQEx2z0xw8q6oUgB54
- name: plugins:grafana-assistant-app:assistant-cli-user
  uid: plugins_HVEFz3K7GwIxMSNu-yROe94TsQM
- name: plugins:grafana-assistant-app:assistant-cloud-mcp-user
  uid: plugins_NzJwMMeQmbzkBhQrWbTf14SnFqU
- name: plugins:grafana-assistant-app:assistant-investigation-user
  uid: plugins_5YP3kORYcRlPoQZGTtvz8D0LzcU
- name: plugins:grafana-assistant-app:assistant-mcp-user
  uid: plugins_kJ5iDjJI8ozroaF2LFfv557xRmk
- name: plugins:grafana-assistant-app:assistant-sandbox-admin
  uid: plugins_UsoERz8Dp08bUnrvZYM-1n_lk5Q
- name: plugins:grafana-assistant-app:assistant-system-investigation-viewer
  uid: plugins_4IlxHi-PZBAt2n47dMd1M0hUazM
- name: plugins:grafana-assistant-app:assistant-user
  uid: plugins_G4uPFRZvF6TukV4o2RIOgFIJY58
- name: plugins:grafana-assistant-app:gcx-user
  uid: plugins_Eit_lnlQbNEqwPZlqYpuI-NY0q8
- name: plugins:grafana-attributions-app:cost-attributions-viewer
  uid: plugins_3sZxwBX167f-_xB8gtFZR_etDzU
- name: plugins:grafana-auth-app:writer
  uid: plugins_6YkpqBmtueTcvhdLJQnSQn0YP44
- name: plugins:grafana-cmab-app:billing-and-usage-reader
  uid: plugins_Dw9qIDO6XkmAkQNea5vLGpw0DyA
- name: plugins:grafana-cmab-app:cost-attribution-admin
  uid: plugins_lF_nX_OP8NK5By69-pHXN7GVO9w
- name: plugins:grafana-cmab-app:cost-attribution-reader
  uid: plugins_XuehygAkagTz4kJ5186TVhk3nfw
- name: plugins:grafana-cmab-app:full-admin
  uid: plugins_NOPJR-YsFXqf7d5V9jqxwHHU9Uw
- name: plugins:grafana-cmab-app:invoice-reader
  uid: plugins_RsaZX9iSx9cFobaJ75eCNwN9rKk
- name: plugins:grafana-cmab-app:usage-alerts-admin
  uid: plugins_hfx2x2vFJEfhBgGiA88nyVYuzLw
- name: plugins:grafana-cmab-app:usage-alerts-reader
  uid: plugins_68RFd0HC9XM4urmdiBYpd98eFvA
- name: plugins:grafana-collector-app:collector-app-admin
  uid: plugins_nZmBIqAewQtf97JP4FZOEky4p1s
- name: plugins:grafana-collector-app:collector-app-reader
  uid: plugins_kIM-ufGsszqmFjXpzQD6ihewxL8
- name: plugins:grafana-csp-app:aws-writer
  uid: plugins_45emFpmDXTvOStsXvKgpZQ7cm-w
- name: plugins:grafana-csp-app:azure-writer
  uid: plugins_KJ1uV-ISTfVQ5xURakyoLjjh_d8
- name: plugins:grafana-csp-app:gcp-writer
  uid: plugins_3yc6UtYQTq0_GREcjZVw_WQi6N0
- name: plugins:grafana-csp-app:reader
  uid: plugins_bV90qAzxQEwi0Uc6h3fjYFlKTEo
- name: plugins:grafana-dbo11y-app:admin
  uid: plugins_QX3C-QmZbRHbyMa3ft54lVC_M3M
- name: plugins:grafana-dbo11y-app:reader
  uid: plugins_kE4Pz8EHTnFcMB3WzIKrTH22d1Q
- name: plugins:grafana-easystart-app:integrations-admin
  uid: plugins_meJiquPt8WKdJpu_QnCr2FPUcyQ
- name: plugins:grafana-easystart-app:integrations-reader
  uid: plugins_Yp95MZlmGcmtV5AOvNSIF6AYbg0
- name: plugins:grafana-easystart-app:integrations-writer
  uid: plugins_W2JB2hSUnPNhpdwKZl6lyWLFP-Q
- name: plugins:grafana-irm-app:admin
  uid: plugins__-TX6YZWQhggpBR-7b8z1LX3o8U
- name: plugins:grafana-irm-app:alert-groups-direct-paging
  uid: plugins_abUMuLfDA7DqXzcTtk5kmGK5VaM
- name: plugins:grafana-irm-app:alert-groups-editor
  uid: plugins_X7Z-gOcvQvAKzb8FWM1-HbqDUnc
- name: plugins:grafana-irm-app:alert-groups-reader
  uid: plugins_txlRQ-GPGDKc6ghfWE_eH7SJQQk
- name: plugins:grafana-irm-app:api-keys-editor
  uid: plugins_i0qnFwBWUdEagqk1jBPyPdkitG4
- name: plugins:grafana-irm-app:api-keys-reader
  uid: plugins_zq7XsvGprUh4M4aE36JSW335SFw
- name: plugins:grafana-irm-app:chatops-editor
  uid: plugins_wapB6R_eQ6Cj1hw2DD1cmb3kfQ4
- name: plugins:grafana-irm-app:chatops-reader
  uid: plugins_4wpJE82vM0bo-K4uAdwUgLgEJTQ
- name: plugins:grafana-irm-app:editor
  uid: plugins_PD5KYyIWBXC_JguPxf_eHLexKZA
- name: plugins:grafana-irm-app:escalation-chains-editor
  uid: plugins_HlShcEd1Xcr_sF2xBp4H-rOiyfU
- name: plugins:grafana-irm-app:escalation-chains-reader
  uid: plugins_70KO5ECPLnVm8PMr0ztZhhjsFPc
- name: plugins:grafana-irm-app:incident-access
  uid: plugins_QbCwQ5k6AmCmNxRpa9G1rmpK4w8
- name: plugins:grafana-irm-app:integrations-editor
  uid: plugins_m1KIpLLguOcc6KmDB6lHf9_tX7E
- name: plugins:grafana-irm-app:integrations-reader
  uid: plugins_5h0OuHDjj6kUPFzRHYLgQbpBl-k
- name: plugins:grafana-irm-app:maintenance-editor
  uid: plugins_b79qyo7HbBmrx2bDZvUNzEIwF7g
- name: plugins:grafana-irm-app:maintenance-reader
  uid: plugins_7owoFGY32AAaye5kBUf2GEMLAoA
- name: plugins:grafana-irm-app:notification-settings-editor
  uid: plugins_UMPo4f5A4NR5P-rCpFeM9bXx29s
- name: plugins:grafana-irm-app:notification-settings-reader
  uid: plugins_sGDHOD8Mne1D7yAj5xOX2_nwO6o
- name: plugins:grafana-irm-app:notifications-receiver
  uid: plugins_TeDZNfttUzmiIOfU_tP312CHzXM
- name: plugins:grafana-irm-app:oncaller
  uid: plugins__XrCMjU1jJxS5BHmz3uGBvTDuPI
- name: plugins:grafana-irm-app:outgoing-webhooks-editor
  uid: plugins_Gdl5lvolDMeG6NmpFt0XceIGsWs
- name: plugins:grafana-irm-app:outgoing-webhooks-reader
  uid: plugins_bbh9Ecb179IGwqoQfJR1Y14AcPU
- name: plugins:grafana-irm-app:reader
  uid: plugins_6O54QVNAXOsJ-ULTCRWNwFvx54E
- name: plugins:grafana-irm-app:schedules-editor
  uid: plugins_SiUG0TOiRZRHgqgsYnJ0L9SySMQ
- name: plugins:grafana-irm-app:schedules-reader
  uid: plugins_-DYGckphX3RVmvGp1_utHornxa4
- name: plugins:grafana-irm-app:settings-editor
  uid: plugins_lZ94sZkwmIQqdl-u1-thNcep8j4
- name: plugins:grafana-irm-app:settings-reader
  uid: plugins_qHXMDYxGGsilbWW8PrGbQaDYhLg
- name: plugins:grafana-irm-app:user-settings-admin
  uid: plugins_HnnYq2ZfViQMid3xXr3SRWXEOzw
- name: plugins:grafana-irm-app:user-settings-editor
  uid: plugins_-kI0MHMskqWlihRXZECoE7bMos8
- name: plugins:grafana-irm-app:user-settings-reader
  uid: plugins_zgHsr4TpZ2Ka6-5lbdm-tGTVqaQ
- name: plugins:grafana-k8s-app:admin
  uid: plugins_XLOJmkOOoWIc-msCEN5auFXvQ0s
- name: plugins:grafana-k8s-app:reader
  uid: plugins_Qhx9LErs5fnRsFs7yPgGRzHDDzs
- name: plugins:grafana-kowalski-app:frontend-observability-admin
  uid: plugins_5-W6E3qMEyOYNSuRow3CKQG4-zU
- name: plugins:grafana-kowalski-app:frontend-observability-editor
  uid: plugins_xLeiaEUmf_FA3OEf2dJvuU9C6Ms
- name: plugins:grafana-kowalski-app:frontend-observability-sourcemap-uploader
  uid: plugins_V0_6E2opVn3C-dA8MsZXgXZ9-dM
- name: plugins:grafana-kowalski-app:frontend-observability-viewer
  uid: plugins_8XqiOKGUBGEUHV8jgiQgiTYZ3bg
- name: plugins:grafana-labels-app:labels-reader
  uid: plugins_RL3T5c7li2glWDn2iLKcGGUUvfg
- name: plugins:grafana-labels-app:labels-writer
  uid: plugins_gzpJ1K-WsbOj6KWeosi_NxY9_kI
- name: plugins:grafana-ml-app:ml-editor
  uid: plugins__ljInUbBXyWU2DPNDvQkijx0HbA
- name: plugins:grafana-ml-app:ml-viewer
  uid: plugins_YFDg8MrVtYhvdtSkB4WShEET5Eo
- name: plugins:grafana-ml-app:sift-editor
  uid: plugins_rsZqmFWHL8BHPskW66H2xSttbBM
- name: plugins:grafana-ml-app:sift-viewer
  uid: plugins_OSWdJ1TeFzTRr7i0fbFRgN20JbY
- name: plugins:grafana-pathfinder-app:interactive-learning-user
  uid: plugins_lGUAcTXh1tDh1OdGIkH63tRqzJ4
- name: plugins:grafana-pdc-app:private-networks-read
  uid: plugins_XZ4_EzfEYIOMeSPqa9BKvvygHuE
- name: plugins:grafana-pdc-app:private-networks-write
  uid: plugins_zUxe1m_eOFb7P4Ry1ESjzcuvrys
- name: plugins:grafana-sigil-app:sigil-admin
  uid: plugins_23uEHsmOGZ9CXyyyB4rN8U94kqQ
- name: plugins:grafana-sigil-app:sigil-data-reader
  uid: plugins_t2d1pFLTVonaaijrAoHCbfDq3XM
- name: plugins:grafana-sigil-app:sigil-feedback-writer
  uid: plugins_bsLWVUP3K5-of_ign6WRgRH7F24
- name: plugins:grafana-sigil-app:sigil-reader
  uid: plugins_bIkKdr4o1NrFALqh5zZ1L_azCPw
- name: plugins:grafana-sigil-app:sigil-viewer
  uid: plugins_YOpcQbhznPw6FgxcrJ0Zvjgk0UQ
- name: plugins:grafana-slo-app:slo-admin
  uid: plugins_4o1UMh4INzhESIQJDchEmkST92Q
- name: plugins:grafana-slo-app:slo-reader
  uid: plugins_C0KHdRF3ZvlzRXxstIFqIb82NbU
- name: plugins:grafana-slo-app:slo-writer
  uid: plugins_tfx9rD8sVwXUdbtiFFBVOfYP4fo
- name: plugins:grafana-synthetic-monitoring-app:access-tokens-writer
  uid: plugins_CHHMGAre-N3yqSbcWu37ViIUTzg
- name: plugins:grafana-synthetic-monitoring-app:admin
  uid: plugins_XoKF32xtq2zqQsXPukeaflCX6OQ
- name: plugins:grafana-synthetic-monitoring-app:alerts-reader
  uid: plugins_4-16SHSLbut8Dbq1yquHHgJQnfg
- name: plugins:grafana-synthetic-monitoring-app:alerts-writer
  uid: plugins_AUIz7SgVBMUldXQVrwjRdab7Tlo
- name: plugins:grafana-synthetic-monitoring-app:checks-reader
  uid: plugins_L29tXYrdVTNAYJtWwV0L647PlXY
- name: plugins:grafana-synthetic-monitoring-app:checks-writer
  uid: plugins_er81afr-nyrJlnxo3k0a7lQraac
- name: plugins:grafana-synthetic-monitoring-app:editor
  uid: plugins_Su68sXSwMWLkeVurx9Ui1BYLLkE
- name: plugins:grafana-synthetic-monitoring-app:probes-reader
  uid: plugins_gawkZpblRFBYaJRWa1X745MCHJQ
- name: plugins:grafana-synthetic-monitoring-app:probes-writer
  uid: plugins_i1yXQlG2y8zcXnJYyzh2R4YVj4A
- name: plugins:grafana-synthetic-monitoring-app:reader
  uid: plugins_Ve2dGixdJGW-L-EJOcYBy9Xbfxc
- name: plugins:grafana-synthetic-monitoring-app:thresholds-reader
  uid: plugins_AKQELp7kDFIhgEBNe3QGOYOuXdM
- name: plugins:grafana-synthetic-monitoring-app:thresholds-writer
  uid: plugins_5uOMCy1w4x7qVFzE9BrKQritDVk
- name: plugins:k6-app:admin
  uid: plugins_JA566OrYaxV4UP2KwHGW_Z0usSU
- name: plugins:k6-app:editor
  uid: plugins_Bf5-jOw4JvW4C_9e62mnFxUWFFw
- name: plugins:k6-app:reader
  uid: plugins_3CjSWRntyKRwbJEmgNtKn4A3o4U
